### ISSUE TITLE
allow searching responses

### ISSUE THREAD

**Issue by bbodenmiller** [milton-lai/saml-chrome-panel#3]
Would be great if I could do a CTRL+F and search the response.

**Comment by milton-lai** [comment]
I will try to look at this soon. It may not be the CTRL+F, since thats taken by Chrome itself, but I may add a little search icon, which'll trigger the CodeMirror search function.

**Comment by milton-lai** [comment]
Added search functionality in 1.8.9. It will search the SAML response only as part of the CodeMirror widget.
