### ISSUE TITLE
SAML Chrome panel fails to detect SAML POST messages

### ISSUE THREAD

**Issue by mrvanes** [milton-lai/saml-chrome-panel#4]
At this moment, SAML Chrome panel fails to detect SAML POST messages. I'm using Chrome 61.0.3163.100 (Official Build) (64-bit) and SAML Chrome panel 1.8.7.

**Comment by milton-lai** [comment]
Hey @mrvanes ,
Sorry for the late reply.
I've tested it on Version 61.0.3163.100 (Official Build) (64-bit) on OSX with 1.8.7, and it looks like it is working as far as I can tell. Feel free to PM me your login link to try it with. I can also send you a test end point to try to confirm whether its all working or not.
Thanks,
Milton

**Comment by mrvanes** [comment]
Yes, I've seen intermittant behaviour. Some POSTs are detected and some are not. Will try to find the discerning parameter if I can! Can't give you the link to SP becuase it's internal test...

**Comment by skoranda** [comment]
I can reproduce on 61.0.3163.100 for Mac OS with 1.8.7. Would it assist you with troubleshooting if I sent you the SAML assertion from the IdP sent to the SP via the POST?

**Comment by milton-lai** [comment]
If its possible to send it to me (maybe even the export), that would help greatly.
I'm essentially parsing the URL's and post data to see if I can detect it is SAML. I'll need to see it so I can figure out your scenario.

**Comment by mrvanes** [comment]
Could it perhaps be linked to this bug in Chrome?
https://bugs.chromium.org/p/chromium/issues/detail?id=766715

**Comment by skoranda** [comment]
@mrvanes @milton-lai I suspect so, yes. Thanks. I will hold off sending an example SAML assertion for now given thatmy failing use cases involves an assertion sent with a 302.

**Comment by milton-lai** [comment]
Thanks guys for looking into it. 
If the record shows in your chrome network tab, then I should have access to it.
I'll leave this issue open for now to keep this going.

**Comment by mrvanes** [comment]
I think this is solved in Chrome 63.
