### ISSUE TITLE
Causes massive memory leaks

### ISSUE THREAD

**Issue by mrchief** [milton-lai/saml-chrome-panel#5]
If you leave the extension enabled, it causes massive memory leaks. E.g., I noticed that my Okta homepage tab was leaking massive memory if left open overnight:

this is over a 24 hour period
![image](https://user-images.githubusercontent.com/781818/32840060-89193644-c9e4-11e7-9cac-0265a67044e5.png)

this one over 48 hours
![image](https://user-images.githubusercontent.com/781818/32840106-a7fa7bea-c9e4-11e7-933b-d1043d6e7ed6.png)

I first thought it was the website that leaked memory. But doing a heap analysis pointed out that an extension prevented 92% of resources from being GCed

![image](https://user-images.githubusercontent.com/781818/32840161-db039c10-c9e4-11e7-8ec0-04857f910cf2.png)

That extension turned out to be SAML panel
![image](https://user-images.githubusercontent.com/781818/32840174-e7d24ec8-c9e4-11e7-97b6-67d678e3c9cd.png)

Disabling it confirmed the doubts, dropping memory by over 90%:
![image](https://user-images.githubusercontent.com/781818/32840234-14dec4d2-c9e5-11e7-927d-980ff818e9f2.png)

Please look into this. Thanks!

Chrome: Version 62.0.3202.94 (Official Build) (64-bit)
OS: Windows 7 x64

**Comment by milton-lai** [comment]
Thanks so much for letting me know!
I'm assuming right now, its because I'm still polling all network traffic, as soon as its open, and thus, that is what could cause the memory leak.

I'm not yet sure of a solution, but will have a think today.

**Comment by milton-lai** [comment]
One way might be to limit the amount that I store in an array, but I'd be unsure what a good value is.
In addition, I could create a feature like "Preserve Log", which would keep ALL traffic if toggled, but otherwise, there is a limit of 1000 messages or something like that..

**Comment by mrchief** [comment]
Yes that would be a good idea. 1000 is big number IMO. Human can't track more than 50 at a time and 90% of the time, you'd only want to look at most recent 10-20 requests. SAML heavy apps may want more but I guess most users will only want to track SAML requests for the initial login page. So you could reduce the number a bit if it helps reduce the memory footprint.

Now here's something that'll help, if its possible to do:

 - Track only when Dev tools panel is open
 - Track only when tab is active (if you can't or don't want to pursue option 1)

This should get things under control I think.

**Comment by milton-lai** [comment]
@mrchief I've pushed a new change out (1.8.8), so hopefully you'll get it soon.
I added a toggle, that is on my default. It sets the max number of network requests to 500. I set it to 500 because some pages can load a lot of requests after your SAML request has appeared, so we won't want it to drop off. In any case, its a toggle, so you can turn it off to keep more than 500.

Thanks again for raising the issue. Let me know if there are any other issues!
