### ISSUE TITLE
SAML tab doesn't always show up

### ISSUE THREAD

**Issue by crazedmeph** [milton-lai/saml-chrome-panel#8]
Not really sure why but sometimes i can see the tab in dev tools and sometimes i cannot. The biggest time i cannot see it is when I incognito (with allow in incognito in the extensions tab). To reproduce just open a new incognito tab and press f12. It used to work, not sure what happened. I know chrome just updated so maybe that changed something?

**Comment by ellucianBret** [comment]
I can't get it to show at all now! I am on Chrome version 83.0.4103.61

**Comment by milton-lai** [comment]
Thanks for the heads up. I’ll find time this evening and over the weekend to try to sort it out.

**Comment by milton-lai** [comment]
I've had a quick look this morning, and it seems it might be related to Chrome. 
The suggestion here helped out with non-incognito mode:
https://github.com/facebook/react/issues/19002#issuecomment-637462179

The interesting thing is that all my additional chrome extensions are disappearing as well.

**Comment by milton-lai** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1093731
Link regarding the bug. Hopefully Chrome #85 (or #84) is out soon.

**Comment by milton-lai** [comment]
@crazedmeph @ellucianBret do you guys mind checking if the latest version has solved the issue? 
Currently on 84.0.4147.89 and it looks OK at this point.

**Comment by ellucianBret** [comment]
@milton-lai - I can confirm that it is currently showing for me right now. It shows as SAMLxx

**Comment by milton-lai** [comment]
SAMLxx - that wasn't meant to happen! it was for my testing! Ill close this issue, but fix that right away!
Thanks @ellucianBret

**Comment by sally2015** [comment]
Why can't I still see it after adding it？
Chrome version: 119.0.6045.123
![image](https://github.com/milton-lai/saml-chrome-panel/assets/14807468/5217bc50-b10d-45b0-a3d0-a78f9d9b00ff)
![截屏2023-11-17 下午4 17 44](https://github.com/milton-lai/saml-chrome-panel/assets/14807468/9b397bba-34b4-4f8f-9980-8ce66f8fb4f9)
