### ISSUE TITLE
Update links no longer works

### ISSUE THREAD

**Issue by korzynski** [milton-lai/saml-chrome-panel#9]
For some reason, the button to “Update all link/form targets to _self” no longer works. When I click it, nothing happens. 
(I just submitted this in the Chrome web store as well)

**Comment by milton-lai** [comment]
@korzynski I "think" I replicated it once, but haven't been able to a second time. What is your browser version + OS?
I'm currently testing on a 88.0.4324.150 - OSX 10.15.7.

The button calls a JS function that finds all "a" and all "form" elements, and sets the target to "_self". Screen below is where its updating google.com's search form.

![image](https://user-images.githubusercontent.com/13580442/107866024-c2729f00-6ec0-11eb-9d72-ece035e26fc9.png)

If your endpoint is public, you can find my email on the contact section of https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace?hl=en and then send me an email with the details and I can take a look.

**Comment by korzynski** [comment]
I'm running Chrome 88.0.4324.150 on Windows 10 Pro build 18363.1316
Should the JS function work on any website with a and form elements? I have tested it on all sorts of pages and the update targets button doesn't seem to do anything. If there are any logs I can generate that would be helpful, I'm happy to.

Here's the error that is generated when I click the button: 

Error handling response: TypeError: Cannot read property 'id' of undefined
    at chrome-extension://fclefbghbkhodbbehdmllkhfbgbnjkme/background.js:13:41

![image](https://user-images.githubusercontent.com/8608320/107869940-bc40dc00-6e48-11eb-91bf-e2450c50fc2e.png)

**Comment by milton-lai** [comment]
Thanks @korzynski for getting back. Interesting!
I'm still unable to replicate, but heres what I've done.

- Removed the chrome.tabs.query as we already have the id in the `request.tabId`.
- Cleaned up the code a bit
- Added more logging.

When you get the time, please install the unpacked version from https://github.com/milton-lai/saml-chrome-panel/tree/feature/update-links (maybe make sure that you update `devtools.js` to rename the tab to `SAML Local` or something, so you know which one you've installed (also best to disable the one from the chrome store). Do make sure you click the refresh button on the extensions tab AND close and reopen the developer tools on the tab you're testing AND + refresh the tab. I was reading that those steps should more or less guarantee that a refresh has properly happened.

 If you open "background page", you'll also get any logging from the background.js file.
![image](https://user-images.githubusercontent.com/13580442/107872402-48610b00-6efe-11eb-9157-0c8763c745d8.png)

And using google as an example:
![image](https://user-images.githubusercontent.com/13580442/107872445-970ea500-6efe-11eb-9929-1211811ce585.png)

Note that my logger is showing all levels.

Please do let me know how it goes!

**Comment by korzynski** [comment]
The updated code appears to work!
![image](https://user-images.githubusercontent.com/8608320/107887870-fbf5db00-6ebd-11eb-94ad-f62ba6b19454.png)

Although the console did log an error, I don't know what it means:
Unchecked runtime.lastError: The message port closed before a response was received.
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)

![image](https://user-images.githubusercontent.com/8608320/107887861-dff23980-6ebd-11eb-916b-23454ec1f30d.png)
